export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  SETUP_USERNAME: "/setup-username",
  PROFILE: "/u/:username",
  USER_PROFILE: "/user/:userId",
  POST: "/post/:postId",
  DASHBOARD: "/dashboard",
  EDITOR: "/editor/:roomId",
  ADMIN: "/admin",
  RESET_PASSWORD: "/reset-password/:token",
  NOT_FOUND: "/404",
};

export const DASHBOARD_SECTIONS = {
  DASHBOARD: "dashboard",
  CP: "cp",
  ROOMS: "rooms",
  LIVE_ROOMS: "live-rooms",
  BOOKMARKS: "bookmarks",
  FEED: "feed",
  FOLLOWING: "following",
  LEADERBOARD: "leaderboard",
  ACHIEVEMENTS: "achievements",
  HISTORY: "history",
  WHITEBOARDS: "whiteboards",
  MESSAGES: "messages",
  NOTIFICATIONS: "notifications",
  PROFILE: "profile",
  PROFILE_ID: "profile/:userId",
  SETTINGS: "settings",
  HELPDESK: "helpdesk",
  PLANNER: "planner",
  SUBSCRIPTION: "subscription",
  TRUST_SAFETY: "trust-safety",
};
